apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: backend
    name: desafio
    namespace: default
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app: backend
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - image: dirceusilva/app-exemplo-prometheus:latest
                  imagePullPolicy: Always
                  name: app-exemplo-prometheus
                  ports:
                      - containerPort: 5000
                        name: http
                        protocol: TCP
                  resources: {}
                  securityContext:
                      allowPrivilegeEscalation: false
                      capabilities: {}
                      privileged: false
                      readOnlyRootFilesystem: false
                      runAsNonRoot: false
                  stdin: true
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  tty: true
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: ingress-backend
    namespace: default
spec:
    rules:
        - host: backend.com.br
          http:
              paths:
                  - backend:
                        serviceName: backend
                        servicePort: 5000
                    pathType: ImplementationSpecific
---
apiVersion: v1
kind: Service
metadata:
    name: backend
    namespace: default
spec:
    ports:
        - name: http
          port: 5000
          protocol: TCP
          targetPort: 5000
    selector:
        app: backend
    sessionAffinity: None
    type: ClusterIP
